# Generated by Django 2.0 on 2020-10-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onesocial_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialprofile',
            unique_together={('network', 'uid')},
        ),
    ]
