# Generated by Django 2.0 on 2020-10-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onesocial_django', '0002_auto_20201021_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='account_token',
            field=models.CharField(max_length=32, unique=True, verbose_name='account token'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='extra_json',
            field=models.TextField(blank=True, null=True, verbose_name='extra data JSON'),
        ),
    ]
